# Generated by Django 5.0 on 2023-12-05 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AGZeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.TextField(choices=[('Montag', 'Montag'), ('Dienstag', 'Dienstag'), ('Mittwoch', 'Mittwoch'), ('Donnerstag', 'Donnerstag'), ('Freitag', 'Freitag')], default='Montag', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Datumsraum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatum', models.DateTimeField()),
                ('enddatum', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raum_nr', models.SmallIntegerField()),
                ('geschoss', models.CharField(max_length=4)),
                ('kapazitaet', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zeitraum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startzeit', models.TimeField()),
                ('endzeit', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(max_length=40)),
                ('is_password_otp', models.BooleanField(default=True)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nutzer')),
                ('rechte_gruppe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_import', 'Can import excel data')],
            },
        ),
        migrations.CreateModel(
            name='AG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beschreibung', models.CharField(max_length=500)),
                ('max_anzahl', models.SmallIntegerField()),
                ('offene_AG', models.BooleanField()),
                ('ag_zeit', models.ManyToManyField(null=True, to='main_app.agzeit')),
                ('angebots_datum_raum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.datumsraum')),
                ('leiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gruppenleiter_leiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.personal')),
                ('raum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.raum')),
            ],
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.CharField(max_length=3)),
                ('tag_id', models.CharField(max_length=100)),
                ('bus_kind', models.BooleanField()),
                ('name_eb', models.CharField(max_length=100)),
                ('kontakt_eb', models.CharField(max_length=300)),
                ('ag_buchungen', models.ManyToManyField(to='main_app.ag')),
                ('gruppen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gruppe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nutzer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_wert', models.CharField(choices=[('GOOD', 'Good'), ('MEDIUM', 'Medium'), ('BAD', 'Bad')], default='MEDIUM', max_length=6)),
                ('schueler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schueler')),
            ],
        ),
        migrations.CreateModel(
            name='Raum_Belegung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_id', models.BigIntegerField()),
                ('ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ag')),
                ('angebots_zeitraum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.datumsraum')),
                ('aufsichtsperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.personal')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.raum')),
                ('angebots_zeit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.zeitraum')),
            ],
        ),
        migrations.CreateModel(
            name='Aufenthalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.raum')),
                ('schueler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.schueler')),
                ('zeitraum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.zeitraum')),
            ],
        ),
        migrations.AddField(
            model_name='agzeit',
            name='zeitraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.zeitraum'),
        ),
    ]
