# Generated by Django 4.2.5 on 2024-01-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ag',
            name='beschreibung',
        ),
        migrations.RemoveField(
            model_name='raum_belegung',
            name='angebots_zeit',
        ),
        migrations.RemoveField(
            model_name='raum_belegung',
            name='angebots_zeitraum',
        ),
        migrations.RemoveField(
            model_name='raum_belegung',
            name='aufsichtsperson',
        ),
        migrations.AlterField(
            model_name='ag',
            name='ag_zeit',
            field=models.ManyToManyField(null=True, to='main_app.agzeit'),
        ),
        migrations.AlterField(
            model_name='raum_belegung',
            name='tablet_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
