# Generated by Django 4.2.5 on 2024-01-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raum_historie',
            name='gruppe',
        ),
    ]
