# Generated by Django 4.2.5 on 2024-01-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raum',
            name='geschoss',
            field=models.CharField(max_length=12),
        ),
    ]
