# Generated by Django 4.2.5 on 2024-01-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_ag_beschreibung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ag',
            name='ag_zeit',
            field=models.ManyToManyField(to='main_app.agzeit'),
        ),
        migrations.AlterField(
            model_name='raum_belegung',
            name='tablet_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
