# Generated by Django 4.2.5 on 2024-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_raum_belegung_tablet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='angemeldet',
            field=models.BooleanField(default=False),
        ),
    ]
